### ISSUE TITLE
Warning message: "le package 'ffbase' n'est pas disponible for this version of R

### ISSUE THREAD

**Issue by melyym** [GPawi/LANDO#3]
Hello,

I'm trying to use LANDO but I'm pretty new in coding (some experience in R)
When I do the install-requirements in Jupyter Notebook I get the message :

```
Warning message:
le package 'ffbase' n'est pas disponible for this version of R

```
I'm using the old version given in the Readme hoping that way it will not give errors but maybe I have to install latest version of R ...
Any ideas ?

Thank you in advance

**Comment by GPawi** [comment]
Hi @melyym - thanks for reporting this issue! 
Technically, 'ffbase' should work for any R version above 2.12.0 and I recommend in the ReadMe that users should install R 4.1.2 for LANDO. So, I reckon that there is an issue with Jupyter Notebook and the IRkernel. Maybe IRkernel isn't using the correct R version. 
But it would be great, if you can share more information on the system that you're using for reproducibility (macOS or Windows, which R version do you have installed in R studio).
What you could do to find out, which R version the IRkernel is using in Jupyter Notebook:
1. Open Jupyter Notebook and go to the "install-requirements" notebook.
2. When it is ready, left mouse click on the left side of the first cell to select the entire cell (it should be a grey area that says "In [ ]:" or maybe "In [1]:").
3. Press "A" on your keyboard to insert a new cell above the first cell.
4. Just to make sure everything is correct: On the right hand side in the small drop-down menu it should say "SoS" for "SoS notebook".
5. Now enter into the new cell the following command: `!R R --version` and execute the cell.
6. Please then copy what the output is and share it here, then we can work from there to fix the issue for you. :) 

Sorry that the process is causing you some trouble, but hopefully it works soon.

Gregor

**Comment by GPawi** [comment]
Hi @melyym - do you have a status update for me? :)

**Comment by GPawi** [comment]
Hi @melyym 
I haven't heard back from you, so I will close the issue for now in the hope that the issue was resolved. Please feel free to reopen it. 

Gregor

**Comment by GPawi** [comment]
Hi @melyym 
I found out now what the issue was:
Apparently the ffbase package was taken down from CRAN repository (https://github.com/edwindj/ffbase/issues/62). I have fixed that now and during the installation LANDO will load the package from Github. 
Thanks again for bringing this to my attention and sorry for any inconvenience caused!

Best regards,
Gregor

**Comment by melyym** [comment]
Hello !

I'm sorry I did not had the time to answer you back, been a long time I did not had to chance to get back to LANDO.
Thank you very much for the help, I get back to you if any problem when I try again !

Thank you again

Melanie
